[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
router = "74EXxDQkbybAivua2WKhVcHSmeyiXp47mmqVwGT5dc2s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
program = "pumpfun.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "G7RdYEyuuqWa5Fwn3iVs99LyNcwVUE5hbaQEL8cUpump"

[[test.validator.clone]]
address = "4wTV1YmiEkRvAtNtsSGPtUrqRYQMe5SKy2uB4Jjaxnjf"

[[test.validator.clone]]
address = "9KVkzgk6A3dNPxGvSJkBmg6VaciErEKsSSizpYRQJEzb"

[[test.validator.clone]]
address = "CebN5WGQ4jvEPvsVU4EoHEpgzq1VV7AbicfhtW4xC9iM"
